services:
  drupal:
    image: drupal:9
    ports:
      - "8080:80"
    restart: always

  postgres:
    image: postgres:14
    environment:
    - POSTGRES_PASSWORD=mypasswd
    - POSTGRES_DB=drupal
    - POSTGRES_USER=user
    restart: always
    